services:
  db:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: angiocardio
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: angiocardiodb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: nextjs_app
    environment:
      DATABASE_URL: "postgresql://angiocardio:123456@db:5432/angiocardiodb?schema=public"
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  pgdata: