version: '3.8'
services:
  app:
    build:
      context: .
    container_name: nextjs_app
    environment:
      DATABASE_URL: "postgresql://postgres.vsggwoiusqfbkuvywhyd:angiocardio2025@aws-0-sa-east-1.pooler.supabase.com:5432/postgres"
    ports:
      - "3000:3000"

volumes:
  pgdata: